# Pin Constraints for Xilinx FPGA
#
# Target: Xilinx Artix-7 (e.g., Arty A7-100T board)
# Format: XDC (Xilinx Design Constraints)
#
# Usage: Used by Vivado synthesis and implementation
#   read_xdc pins.xdc

# ============================================================================
# Clock Inputs
# ============================================================================

# System clock: 100 MHz differential clock
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports sys_clk_p]
set_property -dict {PACKAGE_PIN D3 IOSTANDARD LVCMOS33} [get_ports sys_clk_n]

# Create differential clock buffer
# create_clock -period 10.000 -name sys_clk [get_ports sys_clk_p]

# Alternative: Single-ended clock
# set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports sys_clk]

# ============================================================================
# Reset Button
# ============================================================================

# CPU reset button (active high, with pulldown)
set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33} [get_ports sys_rst]
set_property PULLDOWN true [get_ports sys_rst]

# ============================================================================
# AXI4-Lite Interface
# ============================================================================

# Write address channel
set_property -dict {PACKAGE_PIN A8 IOSTANDARD LVCMOS33} [get_ports axi_awvalid]
set_property -dict {PACKAGE_PIN A9 IOSTANDARD LVCMOS33} [get_ports axi_awready]

set_property -dict {PACKAGE_PIN A10 IOSTANDARD LVCMOS33} [get_ports {axi_awaddr[0]}]
set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVCMOS33} [get_ports {axi_awaddr[1]}]
set_property -dict {PACKAGE_PIN B10 IOSTANDARD LVCMOS33} [get_ports {axi_awaddr[2]}]
set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS33} [get_ports {axi_awaddr[3]}]
set_property -dict {PACKAGE_PIN C10 IOSTANDARD LVCMOS33} [get_ports {axi_awaddr[4]}]
set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVCMOS33} [get_ports {axi_awaddr[5]}]
set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVCMOS33} [get_ports {axi_awaddr[6]}]
set_property -dict {PACKAGE_PIN D11 IOSTANDARD LVCMOS33} [get_ports {axi_awaddr[7]}]
# ... (continue for full 32-bit address)

# Write data channel
set_property -dict {PACKAGE_PIN E10 IOSTANDARD LVCMOS33} [get_ports axi_wvalid]
set_property -dict {PACKAGE_PIN E11 IOSTANDARD LVCMOS33} [get_ports axi_wready]

set_property -dict {PACKAGE_PIN F10 IOSTANDARD LVCMOS33} [get_ports {axi_wdata[0]}]
set_property -dict {PACKAGE_PIN F11 IOSTANDARD LVCMOS33} [get_ports {axi_wdata[1]}]
# ... (32-bit data bus)

# Write response channel
set_property -dict {PACKAGE_PIN G10 IOSTANDARD LVCMOS33} [get_ports axi_bvalid]
set_property -dict {PACKAGE_PIN G11 IOSTANDARD LVCMOS33} [get_ports axi_bready]
set_property -dict {PACKAGE_PIN H10 IOSTANDARD LVCMOS33} [get_ports {axi_bresp[0]}]
set_property -dict {PACKAGE_PIN H11 IOSTANDARD LVCMOS33} [get_ports {axi_bresp[1]}]

# ============================================================================
# Video Output - HDMI/DVI
# ============================================================================

# HDMI TX (via ADV7511 or similar)
# Note: Arty A7 uses PMOD connectors for video, adjust as needed

# TMDS data lanes (differential)
set_property -dict {PACKAGE_PIN D19 IOSTANDARD TMDS_33} [get_ports {hdmi_tx_p[0]}]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD TMDS_33} [get_ports {hdmi_tx_n[0]}]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD TMDS_33} [get_ports {hdmi_tx_p[1]}]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD TMDS_33} [get_ports {hdmi_tx_n[1]}]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD TMDS_33} [get_ports {hdmi_tx_p[2]}]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD TMDS_33} [get_ports {hdmi_tx_n[2]}]

# TMDS clock (differential)
set_property -dict {PACKAGE_PIN E19 IOSTANDARD TMDS_33} [get_ports hdmi_tx_clk_p]
set_property -dict {PACKAGE_PIN E20 IOSTANDARD TMDS_33} [get_ports hdmi_tx_clk_n]

# Alternative: VGA output (12-bit color)
# set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS33} [get_ports {vga_r[0]}]
# ... (RGB channels, hsync, vsync)

# ============================================================================
# External Memory Interface - DDR3
# ============================================================================

# DDR3 is typically connected via MIG (Memory Interface Generator)
# These constraints would be auto-generated by MIG IP

# Address and control
set_property -dict {PACKAGE_PIN R2 IOSTANDARD SSTL15} [get_ports {ddr3_addr[0]}]
set_property -dict {PACKAGE_PIN R3 IOSTANDARD SSTL15} [get_ports {ddr3_addr[1]}]
# ... (14-bit address)

set_property -dict {PACKAGE_PIN K2 IOSTANDARD SSTL15} [get_ports {ddr3_ba[0]}]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD SSTL15} [get_ports {ddr3_ba[1]}]
set_property -dict {PACKAGE_PIN L2 IOSTANDARD SSTL15} [get_ports {ddr3_ba[2]}]

set_property -dict {PACKAGE_PIN J4 IOSTANDARD SSTL15} [get_ports ddr3_ras_n]
set_property -dict {PACKAGE_PIN K4 IOSTANDARD SSTL15} [get_ports ddr3_cas_n]
set_property -dict {PACKAGE_PIN L4 IOSTANDARD SSTL15} [get_ports ddr3_we_n]

# Data strobe (differential)
set_property -dict {PACKAGE_PIN N2 IOSTANDARD DIFF_SSTL15} [get_ports {ddr3_dqs_p[0]}]
set_property -dict {PACKAGE_PIN N1 IOSTANDARD DIFF_SSTL15} [get_ports {ddr3_dqs_n[0]}]

# Data bus (16-bit for typical Artix-7 config)
set_property -dict {PACKAGE_PIN R5 IOSTANDARD SSTL15} [get_ports {ddr3_dq[0]}]
set_property -dict {PACKAGE_PIN P5 IOSTANDARD SSTL15} [get_ports {ddr3_dq[1]}]
# ... (16-bit data)

# Clock (differential)
set_property -dict {PACKAGE_PIN U9 IOSTANDARD DIFF_SSTL15} [get_ports ddr3_clk_p]
set_property -dict {PACKAGE_PIN V9 IOSTANDARD DIFF_SSTL15} [get_ports ddr3_clk_n]

# ============================================================================
# Debug LEDs
# ============================================================================

set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS33} [get_ports {led[1]}]
set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS33} [get_ports {led[2]}]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {led[3]}]

# RGB LEDs (if available)
set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS33} [get_ports {led_rgb[0]}]  # Red
set_property -dict {PACKAGE_PIN F6 IOSTANDARD LVCMOS33} [get_ports {led_rgb[1]}]  # Green
set_property -dict {PACKAGE_PIN G6 IOSTANDARD LVCMOS33} [get_ports {led_rgb[2]}]  # Blue

# ============================================================================
# Debug UART
# ============================================================================

set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVCMOS33} [get_ports uart_tx]
set_property -dict {PACKAGE_PIN A9 IOSTANDARD LVCMOS33} [get_ports uart_rx]

# ============================================================================
# GPIO / PMOD Connectors
# ============================================================================

# PMOD JA (8 pins)
set_property -dict {PACKAGE_PIN G13 IOSTANDARD LVCMOS33} [get_ports {pmod_ja[0]}]
set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS33} [get_ports {pmod_ja[1]}]
set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVCMOS33} [get_ports {pmod_ja[2]}]
set_property -dict {PACKAGE_PIN D12 IOSTANDARD LVCMOS33} [get_ports {pmod_ja[3]}]
set_property -dict {PACKAGE_PIN D13 IOSTANDARD LVCMOS33} [get_ports {pmod_ja[4]}]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS33} [get_ports {pmod_ja[5]}]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS33} [get_ports {pmod_ja[6]}]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports {pmod_ja[7]}]

# ============================================================================
# Configuration and Special Pins
# ============================================================================

# Configuration mode: Master SPI
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

# Bitstream configuration
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

# ============================================================================
# I/O Standards and Drive Strength
# ============================================================================

# Set slew rate for non-critical outputs
set_property SLEW SLOW [get_ports led*]

# Drive strength for video outputs (high current)
set_property DRIVE 8 [get_ports hdmi_tx*]

# Input delay groups for synchronous interfaces
# (See timing.xdc for detailed timing constraints)

# ============================================================================
# Notes
# ============================================================================

# Pin assignments are for Digilent Arty A7-100T board
# Adjust as needed for your specific board
#
# Xilinx 7-series I/O standards:
# - LVCMOS33: 3.3V CMOS
# - LVCMOS25: 2.5V CMOS
# - SSTL15: DDR3 I/O
# - TMDS_33: HDMI/DVI differential signaling
#
# To check for conflicts:
#   report_io -verbose
#   report_drc -verbose
#
# Generate pin report:
#   report_io -file design_io.rpt
