//! UPF (IEEE 1801) emission from the checked power-domain model.
//!
//! The power model lives in the IR (spec power-domain subset); UPF is ONE
//! backend — an interchange export for third-party ASIC implementation
//! flows. The native flow consumes the model directly and never reads this
//! file back.
//!
//! Emitted per design (when `power_domain` declarations exist):
//! - `create_supply_port` / `create_supply_net` per external supply
//! - `create_supply_net` per derived domain
//! - `create_power_domain` with `-elements` from `#[power_domain]`-bound
//!   entity instances (containment: unbound children inherit, so only
//!   explicitly-bound roots need listing)
//! - `create_power_switch` for `switched(...)` domains, with
//!   `on_state`/`off_state` Booleans from the declared `on_when` expression
//! - `add_power_state` per declared supply state

use crate::mir::{Mir, Module};
use skalp_frontend::hir::{Hir, HirPowerCtrl, HirPowerDerivation};

/// Generate UPF text for a design, or None when no power domains are declared.
pub fn generate_upf(hir: &Hir, mir: &Mir, top_name: &str) -> Option<String> {
    if hir.power_domain_decls.is_empty() {
        return None;
    }

    let mut out = String::new();
    out.push_str("# UPF generated by the SKALP compiler from power_domain declarations.\n");
    out.push_str("# The checked model in the source is authoritative; do not hand-edit.\n");
    out.push_str("upf_version 2.1\n\n");

    // Supply ports/nets
    for decl in &hir.power_domain_decls {
        match &decl.derivation {
            HirPowerDerivation::External => {
                out.push_str(&format!(
                    "create_supply_port {}\n",
                    decl.name.to_uppercase()
                ));
                out.push_str(&format!("create_supply_net {}\n", decl.name.to_uppercase()));
                out.push_str(&format!(
                    "connect_supply_net {0} -ports {0}\n",
                    decl.name.to_uppercase()
                ));
            }
            HirPowerDerivation::Regulated { macro_name, .. } => {
                out.push_str(&format!("create_supply_net {}\n", decl.name.to_uppercase()));
                if let Some(m) = macro_name {
                    out.push_str(&format!(
                        "# {} is driven by regulator macro instance `{}` (analog IP)\n",
                        decl.name.to_uppercase(),
                        m
                    ));
                }
            }
            HirPowerDerivation::Switched { .. } => {
                out.push_str(&format!("create_supply_net {}\n", decl.name.to_uppercase()));
            }
        }
    }
    out.push('\n');

    // Instance paths per bound entity (walk the MIR instance tree from top)
    let top = mir.modules.iter().find(|m| m.name == top_name);
    for decl in &hir.power_domain_decls {
        let bound_entities: Vec<&str> = hir
            .entities
            .iter()
            .filter(|e| {
                e.power_domain_config
                    .as_ref()
                    .is_some_and(|c| c.domain_name == decl.name)
            })
            .map(|e| e.name.as_str())
            .collect();

        let mut elements: Vec<String> = Vec::new();
        if let Some(top) = top {
            if bound_entities.contains(&top.name.as_str()) {
                elements.push(".".to_string()); // whole design
            }
            collect_instance_paths(mir, top, "", &bound_entities, &mut elements, 0);
        }

        out.push_str(&format!(
            "create_power_domain PD_{}{}\n",
            decl.name,
            if elements.is_empty() {
                String::new()
            } else {
                format!(" -elements {{{}}}", elements.join(" "))
            }
        ));
        out.push_str(&format!(
            "create_supply_set SS_{0} -function {{power {1}}} -function {{ground VSS}}\n",
            decl.name,
            decl.name.to_uppercase()
        ));
    }
    out.push('\n');

    // Power switches for switched domains
    for decl in &hir.power_domain_decls {
        if let HirPowerDerivation::Switched {
            parent,
            on_when,
            ack_on,
        } = &decl.derivation
        {
            out.push_str(&format!(
                "create_power_switch SW_{} -domain PD_{}\\\n",
                decl.name, decl.name
            ));
            out.push_str(&format!(
                "    -input_supply_port {{sw_in {}}}\\\n",
                parent.to_uppercase()
            ));
            out.push_str(&format!(
                "    -output_supply_port {{sw_out {}}}\\\n",
                decl.name.to_uppercase()
            ));
            if let Some(ctrl) = on_when {
                let net = ctrl_net(ctrl);
                let on_expr = if ctrl.inverted {
                    format!("!{}", net)
                } else {
                    net.clone()
                };
                let off_expr = if ctrl.inverted {
                    net.clone()
                } else {
                    format!("!{}", net)
                };
                out.push_str(&format!("    -control_port {{sw_ctrl {}}}\\\n", net));
                out.push_str(&format!("    -on_state {{on_s sw_in {{{}}}}}\\\n", on_expr));
                out.push_str(&format!("    -off_state {{off_s {{{}}}}}", off_expr));
            }
            if let Some(ack) = ack_on {
                let net = ctrl_net(ack);
                let sense = if ack.inverted {
                    format!("!{}", net)
                } else {
                    net.clone()
                };
                out.push_str(&format!(
                    "\\\n    -ack_port {{sw_ack {} {{{}}}}}",
                    net, sense
                ));
            }
            out.push('\n');
        }
    }
    out.push('\n');

    // System power state table (legal cross-domain combinations)
    if let Some(pst) = &hir.power_states_decl {
        if let Some(first) = pst.states.first() {
            let supplies: Vec<String> = first
                .assignments
                .iter()
                .map(|(d, _)| d.to_uppercase())
                .collect();
            out.push_str(&format!(
                "create_pst SYSTEM_PST -supplies {{{}}}
",
                supplies.join(" ")
            ));
            for sys in &pst.states {
                let states: Vec<String> = first
                    .assignments
                    .iter()
                    .map(|(d, _)| {
                        sys.assignments
                            .iter()
                            .find(|(dd, _)| dd == d)
                            .map(|(_, s)| s.clone())
                            .unwrap_or_else(|| "on".to_string())
                    })
                    .collect();
                out.push_str(&format!(
                    "add_pst_state {} -pst SYSTEM_PST -state {{{}}}
",
                    sys.name,
                    states.join(" ")
                ));
            }
            for (i, (from, to)) in pst.transitions.iter().enumerate() {
                out.push_str(&format!(
                    "describe_state_transition T{}_{}_{} -from {{{}}} -to {{{}}}\n",
                    i, from, to, from, to
                ));
            }
            out.push('\n');
        }
    }

    // Power states
    for decl in &hir.power_domain_decls {
        for state in &decl.states {
            match state.voltage_mv {
                Some(mv) => out.push_str(&format!(
                    "add_power_state SS_{} -state {} {{-supply_expr {{power == `{{FULL_ON, {:.2}}}`}}}}\n",
                    decl.name,
                    state.name,
                    mv as f64 / 1000.0
                )),
                None => out.push_str(&format!(
                    "add_power_state SS_{} -state {} {{-supply_expr {{power == `{{OFF}}`}}}}\n",
                    decl.name, state.name
                )),
            }
        }
    }

    Some(out)
}

/// Hierarchical control net name (`pmu.gpu_sleep` -> `pmu/gpu_sleep`).
fn ctrl_net(ctrl: &HirPowerCtrl) -> String {
    ctrl.path.join("/")
}

/// Collect instance paths (slash-separated) of instances whose module name
/// matches a bound entity. Containment means we do NOT recurse below a bound
/// instance — its subtree inherits the domain.
fn collect_instance_paths(
    mir: &Mir,
    module: &Module,
    prefix: &str,
    bound: &[&str],
    out: &mut Vec<String>,
    depth: usize,
) {
    if depth > 64 {
        return;
    }
    for inst in &module.instances {
        let Some(child) = mir.modules.iter().find(|m| m.id == inst.module) else {
            continue;
        };
        let path = if prefix.is_empty() {
            inst.name.clone()
        } else {
            format!("{}/{}", prefix, inst.name)
        };
        if bound.contains(&child.name.as_str()) {
            out.push(path);
        } else {
            collect_instance_paths(mir, child, &path, bound, out, depth + 1);
        }
    }
}
