// Generated by SKALP compiler
// Module: main

module BitOps (
input wire [7:0] a,
input wire [7:0] b,
output wire [7:0] and_result,
output wire [7:0] or_result,
output wire [7:0] xor_result,
output wire [7:0] not_result
);

assign port_2 = (port_0 & port_1)    ;
assign port_3 = (port_0 | port_1)    ;
assign port_4 = (port_0 ^ port_1)    ;
assign port_5 = ~port_0    ;

endmodule

