// Generated by SKALP compiler
// Module: main

module BitIndexing (
input wire [31:0] data,
output wire bit0,
output wire bit31,
output wire [3:0] nibble0,
output wire [7:0] byte0
);

assign port_1 = port_0[0]    ;
assign port_2 = port_0[31]    ;
assign port_3 = port_0[3:0]    ;
assign port_4 = port_0[7:0]    ;

endmodule

