// Generated by SKALP compiler
// Design: main

module BitIndexing (
    input [31:0] data,
    output bit0,
    output bit31,
    output [3:0] nibble0,
    output [7:0] byte0
);

    assign bit0 = data[0];
    assign bit31 = data[31];
    assign nibble0 = data[3:0];
    assign byte0 = data[7:0];

endmodule
