// Generated by SKALP compiler
// Design: main

module BoundingBoxCheck (
    input [95:0] point,
    input [95:0] min_corner,
    input [95:0] max_corner,
    output inside
);

    wire x_in;
    wire y_in;
    wire z_in;

    assign inside = ((x_in && y_in) && z_in);

endmodule
