// Generated by SKALP compiler
// Design: main

module ColorMixer (
    input [95:0] color1,
    input [95:0] color2,
    input [31:0] blend,
    output [95:0] result
);

    wire [31:0] diff_r;
    wire [31:0] diff_g;
    wire [31:0] diff_b;

endmodule
