// Generated by SKALP compiler
// Module: main

module Comparisons (
input wire [7:0] a,
input wire [7:0] b,
output wire eq,
output wire ne,
output wire lt,
output wire gt
);

assign port_2 = ((port_0 == port_1) ? 1 : 0)    ;
assign port_3 = ((port_0 != port_1) ? 1 : 0)    ;
assign port_4 = ((port_0 < port_1) ? 1 : 0)    ;
assign port_5 = ((port_0 > port_1) ? 1 : 0)    ;

endmodule

