// Generated by SKALP compiler
// Design: main

module ComplexExpr (
    input [31:0] a,
    input [31:0] b,
    input [31:0] c,
    output overflow
);

    assign overflow = (((~a[31] & ~b[31]) & c[31]) | ((a[31] & b[31]) & ~c[31]));

endmodule
