// Generated by SKALP compiler
// Design: main

module Comparisons (
    input [7:0] a,
    input [7:0] b,
    output eq,
    output ne,
    output lt,
    output gt
);

    assign eq = ((a == b) ? 1 : 0);
    assign ne = ((a != b) ? 1 : 0);
    assign lt = ((a < b) ? 1 : 0);
    assign gt = ((a > b) ? 1 : 0);

endmodule
