// Generated by SKALP compiler
// Module: main

module ComplexExpr (
input wire [31:0] a,
input wire [31:0] b,
input wire [31:0] c,
output wire overflow
);

assign port_3 = (((~port_0[31] & ~port_1[31]) & port_2[31]) | ((port_0[31] & port_1[31]) & ~port_2[31]))    ;

endmodule

