// Generated by SKALP compiler
// Design: main

module TestComparison (
    input clk,
    input rst,
    input [1:0] x,
    output y
);

    wire result;

    assign y = result;

    always_ff @(posedge clk) begin
        result <= (rst) ? (0) : (((x == 0)) ? (1) : (0));
    end

endmodule
