// Generated by SKALP compiler
// Module: main

module TestComparison (
input wire clk,
input wire rst,
input logic [1:0] x,
output wire y
);

wire result    ;

assign port_3 = sig_0    ;

always_ff @(posedge port_0)     begin
sig_0 <= (port_1 ? 0 : ((port_2 == 0) ? 1 : 0))        ;
    end

endmodule

