// Generated by SKALP compiler
// Module: main

module Counter (
input wire clk,
input wire rst,
output logic [7:0] count
);

logic [7:0] counter    ;

assign port_2 = sig_0    ;

always_ff @(posedge port_0)     begin
if (port_1)         begin
sig_0 <= 0            ;
        end
else         begin
sig_0 <= (sig_0 + 1)            ;
        end
    end

endmodule

