// Generated by SKALP compiler
// Design: main

module Counter (
    input clk,
    input rst,
    output [7:0] count
);

    reg [7:0] counter = 0;

    assign count = counter;

    always_ff @(posedge clk) begin
        if (rst) begin
            counter <= 0;
        end else begin
            counter <= (counter + 1);
        end
    end

endmodule
