// Generated by SKALP compiler
// Design: main

module DotProductClassify (
    input [95:0] a,
    input [95:0] b,
    output [31:0] dot,
    output parallel,
    output perpendicular,
    output opposite
);

    wire [31:0] zero;
    wire [31:0] pos_threshold;

    assign parallel = 0;
    assign perpendicular = 0;
    assign opposite = 0;

endmodule
