// Generated by SKALP compiler
// Design: main

module FPFormats (
    input [15:0] half,
    input [31:0] single,
    input [63:0] double,
    output [15:0] h_out,
    output [31:0] s_out,
    output [63:0] d_out
);

    assign h_out = half;
    assign s_out = single;
    assign d_out = double;

endmodule
