// Generated by SKALP compiler
// Design: main

module FPArithmetic (
    input [31:0] x,
    input [31:0] y,
    output [31:0] sum,
    output [31:0] prod
);

    assign sum = x;
    assign prod = y;

endmodule
