// Generated by SKALP compiler
// Design: main

module FPComponents (
    input [31:0] value,
    output sign,
    output [7:0] exponent,
    output [22:0] mantissa
);

    assign sign = value[31];
    assign exponent = value[30:23];
    assign mantissa = value[22:0];

endmodule
