// Generated by SKALP compiler
// Design: main

module FPLiterals (
    output [31:0] zero,
    output [31:0] one,
    output [31:0] neg_one,
    output [31:0] infinity,
    output [31:0] nan
);

    assign zero = 32;
    assign one = 32;
    assign neg_one = 32;
    assign infinity = 32;
    assign nan = 32;

endmodule
