// Generated by SKALP compiler
// Design: main

module FPSpecialValues (
    input [31:0] value,
    output is_zero,
    output is_nan,
    output is_inf
);

    wire [7:0] exp;
    wire [22:0] mant;

    assign is_zero = (exp == 8);
    assign mant = (mant == 23);
    assign is_inf = (exp == 8);
    assign mant = (mant == 23);
    assign is_nan = (exp == 8);
    assign mant = (mant != 23);

endmodule
