// Generated by SKALP compiler
// Design: main

module FPSignExtract (
    input [31:0] value,
    output sign,
    output [30:0] magnitude
);

    assign sign = value[31];
    assign magnitude = value[30:0];

endmodule
