// Generated by SKALP compiler
// Module: main

module FPVariants (
input logic [15:0] a16,
input logic [31:0] a32,
input logic [63:0] a64,
output logic [15:0] o16,
output logic [31:0] o32,
output logic [63:0] o64
);

assign port_3 = port_0    ;
assign port_4 = port_1    ;
assign port_5 = port_2    ;

endmodule

