// Generated by SKALP compiler
// Design: main

module FPVariants (
    input [15:0] a16,
    input [31:0] a32,
    input [63:0] a64,
    output [15:0] o16,
    output [31:0] o32,
    output [63:0] o64
);

    assign o16 = a16;
    assign o32 = a32;
    assign o64 = a64;

endmodule
