// Generated by SKALP compiler
// Design: main

module MultiVectorOps (
    input [95:0] a,
    input [95:0] b,
    input [95:0] c,
    output [31:0] dot_ab,
    output [31:0] dot_bc,
    output [95:0] sum
);

endmodule
