// Generated by SKALP compiler
// Design: main

module Mux4to1 (
    input [7:0] a,
    input [7:0] b,
    input [7:0] c,
    input [7:0] d,
    input [1:0] sel,
    output [7:0] out
);

    assign out = ((sel == 0) ? a : ((sel == 1) ? b : ((sel == 2) ? c : ((sel == 3) ? d : 0))));

endmodule
