// Generated by SKALP compiler
// Design: main

module RaySphereHitTest (
    input [95:0] ray_origin,
    input [95:0] ray_direction,
    input [95:0] sphere_center,
    input [31:0] sphere_radius,
    output hit
);

    wire [31:0] oc_x;
    wire [31:0] oc_y;
    wire [31:0] oc_z;
    wire [31:0] t_closest;
    wire [31:0] closest_x;
    wire [31:0] closest_y;
    wire [31:0] closest_z;
    wire [31:0] dist_x;
    wire [31:0] dist_y;
    wire [31:0] dist_z;
    wire [31:0] distance_sq;
    wire [31:0] radius_sq;

    assign hit = 1;

endmodule
