// Generated by SKALP compiler
// Design: main

module ShiftOps (
    input [15:0] data,
    input [3:0] amount,
    output [15:0] shl_result,
    output [15:0] shr_result
);

    assign shl_result = (data << amount);
    assign shr_result = (data >> amount);

endmodule
