// Generated by SKALP compiler
// Module: main

module ShiftOps (
input wire [15:0] data,
input wire [3:0] amount,
output wire [15:0] shl_result,
output wire [15:0] shr_result
);

assign port_2 = (port_0 << port_1)    ;
assign port_3 = (port_0 >> port_1)    ;

endmodule

