// Generated by SKALP compiler
// Design: main

module Vec2Ops (
    input [63:0] a,
    input [63:0] b,
    output [31:0] x_sum,
    output [31:0] y_sum
);

    assign x_sum = (a[31:0] + b[31:0]);
    assign y_sum = (a[63:32] + b[63:32]);

endmodule
