// Generated by SKALP compiler
// Design: main

module Vec2Test (
    input [31:0] v_x,
    input [31:0] v_y,
    output [31:0] x,
    output [31:0] y
);

    assign x = v_x;
    assign y = v_y;

endmodule
