// Generated by SKALP compiler
// Module: main

module Vec2Test (
input logic [63:0] v,
output logic [31:0] x,
output logic [31:0] y
);

assign port_1 = port_0[31:0]    ;
assign port_2 = port_0[63:32]    ;

endmodule

