// Generated by SKALP compiler
// Design: main

module Vec3Clamp (
    input [95:0] v,
    input [95:0] min_val,
    input [95:0] max_val,
    output [95:0] result
);

    wire [31:0] x_clamped;
    wire [31:0] y_clamped;
    wire [31:0] z_clamped;

endmodule
