// Generated by SKALP compiler
// Module: main

module Vec3Test (
input logic [47:0] v,
output wire [15:0] x,
output wire [15:0] y,
output wire [15:0] z
);

assign port_1 = port_0[15:0]    ;
assign port_2 = port_0[31:16]    ;
assign port_3 = port_0[47:32]    ;

endmodule

