// Generated by SKALP compiler
// Design: main

module Vec3Lerp (
    input [95:0] a,
    input [95:0] b,
    input [31:0] t,
    output [95:0] result
);

    wire [31:0] diff_x;
    wire [31:0] diff_y;
    wire [31:0] diff_z;
    wire [31:0] scaled_x;
    wire [31:0] scaled_y;
    wire [31:0] scaled_z;

endmodule
