// Generated by SKALP compiler
// Design: main

module Vec3Distance (
    input [95:0] a,
    input [95:0] b,
    output [31:0] distance_sq
);

    wire [31:0] diff_x;
    wire [31:0] diff_y;
    wire [31:0] diff_z;

    assign distance_sq = (((diff_x * diff_x) + (diff_y * diff_y)) + (diff_z * diff_z));

endmodule
