// Generated by SKALP compiler
// Design: main

module Vec3Ops (
    input [95:0] v,
    output [31:0] x,
    output [31:0] y,
    output [31:0] z
);

    assign x = v[31:0];
    assign y = v[63:32];
    assign z = v[95:64];

endmodule
