// Generated by SKALP compiler
// Design: main

module Vec3Test (
    input [47:0] v,
    output [15:0] x,
    output [15:0] y,
    output [15:0] z
);

    assign x = v[15:0];
    assign y = v[31:16];
    assign z = v[47:32];

endmodule
