// Generated by SKALP compiler
// Design: main

module Vec3Reflect (
    input [95:0] incident,
    input [95:0] normal,
    output [95:0] reflected
);

    wire [31:0] dot_in;
    wire [31:0] two;
    wire [31:0] scale;

endmodule
