// Generated by SKALP compiler
// Design: main

module Vec3Test (
    input [15:0] v_x,
    input [15:0] v_y,
    input [15:0] v_z,
    output [15:0] x,
    output [15:0] y,
    output [15:0] z
);

    assign x = v_x;
    assign y = v_y;
    assign z = v_z;

endmodule
