// Generated by SKALP compiler
// Module: main

module Vec4Test (
input logic [31:0] v,
output wire [7:0] x,
output wire [7:0] y,
output wire [7:0] z,
output wire [7:0] w
);

assign port_1 = port_0[7:0]    ;
assign port_2 = port_0[15:8]    ;
assign port_3 = port_0[23:16]    ;
assign port_4 = port_0[31:24]    ;

endmodule

