// Generated by SKALP compiler
// Design: main

module Vec4Ops (
    input [127:0] v,
    output [31:0] x,
    output [31:0] y,
    output [31:0] z,
    output [31:0] w
);

    assign x = v[31:0];
    assign y = v[63:32];
    assign z = v[95:64];
    assign w = v[127:96];

endmodule
