// Generated by SKALP compiler
// Design: main

module Vec4Test (
    input [31:0] v,
    output [7:0] x,
    output [7:0] y,
    output [7:0] z,
    output [7:0] w
);

    assign x = v[7:0];
    assign y = v[15:8];
    assign z = v[23:16];
    assign w = v[31:24];

endmodule
