// Generated by SKALP compiler
// Design: main

module VecFPMixed (
    input [63:0] v2,
    input [47:0] v3,
    output [31:0] sum2,
    output [15:0] sum3
);

    assign sum2 = (v2[31:0] + v2[63:32]);
    assign sum3 = ((v3[15:0] + v3[31:16]) + v3[47:32]);

endmodule
