name: Quick Check

on:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  quick-check:
    name: Quick Format & Clippy Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-quick-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy (fast mode)
        run: cargo clippy --workspace -- -D warnings

      - name: Build (check only)
        run: cargo check --workspace --all-features

      - name: Run parser regression tests (fast)
        run: cargo test -p skalp-frontend --test parser_regression -- --test-threads=4

      - name: Run HIR builder tests (fast)
        run: cargo test -p skalp-frontend --test hir_builder_regression -- --test-threads=4
